version: '3.4'
services:
  snippetbox:
    restart: always
    depends_on:
      - snippetboxdb
    ports:
      - "4000:4000"
    build:
      dockerfile: Dockerfile
      context: .
  snippetboxdb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - 3306:3306
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"